### ISSUE TITLE
Setup husky for frontend and backend

### ISSUE THREAD

**Issue by avinashupadhya99** [avinashupadhya99/Dictu-Playground#1]
This is to save some time reviewing the code and then changing the linting errors. Which will be done by locally automating this process before committing the code.

[Husky Package](https://www.npmjs.com/package/husky)

**Comment by Diksha02** [comment]
Can I work on this under LGMSOC'21. Also, I just have to set up the husky package, or do I have to automate the changing of linting errors process too?

**Comment by avinashupadhya99** [comment]
Sure, one of the steps in the husky pre commit could be `npm run lint --fix` to auto fix the lint errors. But now that I think about it, it might be a good exprience to auto correct without the developer knowing it. So just linting should be fine. Let me know if you have any questions. Assigning this to you :)

**Comment by Diksha02** [comment]
Yes, I am on it...one question though, I will have to install and set up eslint too in both the directories?

**Comment by avinashupadhya99** [comment]
The backend is not configured with eslint, if you could do that as well, that would be awesome!

**Comment by Diksha02** [comment]
Hey @avinashupadhya99, I just wanted to ask why the readme doesn't show my pic in the contributors' section?
Also, it was my first PR, thank you for guiding me through🙌

**Comment by avinashupadhya99** [comment]
Hey @Diksha02 , well done! 🎉 Thank you for setting it up. Your picture should show up in a while as it usually takes around 24h for it to update.
