### ISSUE TITLE
add some badges with links

### ISSUE THREAD

**Issue by Umesh-01** [avinashupadhya99/Dictu-Playground#10]
![image](https://user-images.githubusercontent.com/83420185/122056064-de526700-ce06-11eb-809c-7384a4bddd9f.png)

## Description 

**I think there should be badges in the README.md file at the top because without them it not looking good enough and attractive.**
**I would like to add badges and also links to these.**

**For example, I will add a PR badge and link to it's web page/ section so that a user can directly go to the web page/section easily using the badge also.**

**Comment by Umesh-01** [comment]
@avinashupadhya99 sir should I do these changes??

**Comment by avinashupadhya99** [comment]
Hey @Umesh-01 , can you please mention what badges do you want to add?

**Comment by Umesh-01** [comment]
@avinashupadhya99 sir I want to add badges for issues (open, closed), PRs (open, close), stars, forks, contributors, and some more...

**Comment by Umesh-01** [comment]
@avinashupadhya99 sir should I add??

**Comment by avinashupadhya99** [comment]
Can you show me an example?

**Comment by Umesh-01** [comment]
@avinashupadhya99 sir check this out, hope it will explain...

![image](https://user-images.githubusercontent.com/83420185/122509039-ad4d7e80-d020-11eb-8522-4574bfc394a8.png)

**Comment by Umesh-01** [comment]
@avinashupadhya99 sir
and also I will add links to them so that it will help the users to navigate to different sections/ webpages like PRs, issues, contributors, etc.

For example, after clicking on the contributors badge the user will be redirected to the contributors web page/ section.

**Comment by Umesh-01** [comment]
@avinashupadhya99 sir should I move forward to do these changes??

**Comment by avinashupadhya99** [comment]
Alright, sure assigning it to you
