### ISSUE TITLE
Add Let'sGrowMore logo under 'Open Source Program' section

### ISSUE THREAD

**Issue by Ayan-thecodeking** [avinashupadhya99/Dictu-Playground#11]
Since this project is part of LGMSOC . I think it's good idea to showcase it in README.md file under Open Source Program section .
I will like to work on this issue under LGMSOC if maintainers agree @avinashupadhya99

**Comment by avinashupadhya99** [comment]
Hey, I'm sorry but I do not feel like that is necessary currently. Hope to you see work on other issues :) Closing it for now
