### ISSUE TITLE
Adding website link in the README.md file📖

### ISSUE THREAD

**Issue by Salonee-Jain** [avinashupadhya99/Dictu-Playground#12]
Navigating through the website would be easier if you have a link of your website on the readme file

**Comment by Salonee-Jain** [comment]
I would like to work on this issue under LGMSOC

**Comment by avinashupadhya99** [comment]
Hey, unfortunately we have not deployed the website yet due to the landing page not being completed. Please look at #3 if you're interested in working on that. I will be closing this issue for now :)
