### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [avinashupadhya99/Dictu-Playground#14]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@avinashupadhya99 pls assign me this issue.

**Comment by avinashupadhya99** [comment]
Hey, like mentioned in #13 and #11 we will not be adding LGM SOC'21 on the readme file. There are UI related issues if you're interested. Please check out #3 for more details :)
