### ISSUE TITLE
Setup guide for windows operating system

### ISSUE THREAD

**Issue by payaldutta** [avinashupadhya99/Dictu-Playground#18]
To describe the step-by-step explanation to run the project on Windows operating system.
Please do assign me under LGMSOC'21. @avinashupadhya99 
Thank You.

** Solution (if required)
* How to setup Docker(specifically for Home edition and Pro edition)
 * npm commands
 * specify API Keys if needed

**Comment by avinashupadhya99** [comment]
Hey, the backend is not yet setup to have such a solution. If you're interested, I can walk you through what the backend does and it is supposed to do and you could work on that. I'll close this issue for now. Let me know if you're interested in working on the backend.
