### ISSUE TITLE
Button to copy the text 

### ISSUE THREAD

**Issue by SamikshaSankar** [avinashupadhya99/Dictu-Playground#2]
In documentation part there are some copy we can copy directly using click copy 
button

I work on this issue under LGM-SOC'21 participant..please assigned me

![copy](https://user-images.githubusercontent.com/52104082/121202205-bc9b3200-c892-11eb-9ecd-3f0075d5cd70.png)

**Comment by avinashupadhya99** [comment]
Hey, can you please give me more context on this? I would be glad to have you contribute as a part of LGM-SOC'21

**Comment by SamikshaSankar** [comment]
Like this
I draw one rectangle on this photo where we can insert copy button..by the help of this button we can copy the commands.
![git4](https://user-images.githubusercontent.com/52104082/121211738-5b775c80-c89a-11eb-862f-8ca50b80a4e1.jpg)

**Comment by Ameenrehman** [comment]
hi @avinashupadhya99  do you want to create a single button to copy the whole content or different button for each line ?
please give some more detail related this issue 
#LGM-SOC

**Comment by avinashupadhya99** [comment]
@SamikshaSankar that is a good idea but currently I do not see much commands in the documentation that would require such a feature to be implemented. Thank you for suggesting! I would be glad to have you contribute in other issues 😄

**Comment by avinashupadhya99** [comment]
Closing this since it is not necessary
