### ISSUE TITLE
adding contributors section in README file

### ISSUE THREAD

**Issue by MukulKolpe** [avinashupadhya99/Dictu-Playground#4]
Hey, I am a participant in LGM-SOC. Can I add the contributor's section in the README file by using 'contributors-img'. So that we can display GitHub profile pictures of all those who have contributed or will contribute to this amazing project. Can you please assign this to me?
Thanks!!!

**Comment by avinashupadhya99** [comment]
Sure, assigning it to you

**Comment by Ayan-thecodeking** [comment]
hey @avinashupadhya99 please assign me if anything is left in readme section 
I'll do that for sure :)
